services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: shipri-client
    restart: unless-stopped
    networks:
      - shipri-network
      - nginx-proxy

networks:
  shipri-network:
    name: shipri-network
  nginx-proxy:
    external: true
