services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: shipri-client
    restart: unless-stopped
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
